services:
  pg_chainlink:
    image: "postgres"
    ports:
      - "5432:5432"
    env_file:
      - database.env
    volumes:
      - ~/Documents/Chainlink/chainlink-rinkeby/.data:/var/lib/postgresql/data
  chainlink:
    restart: always
    image: "smartcontract/chainlink:1.3.0"
    env_file:
      - .env
    depends_on:
      - pg_chainlink
    ports:
      - "6688:6688"
    volumes:
      - ~/Documents/Chainlink/chainlink-rinkeby/.chainlink-volume:/chainlink/
    command: node start --password /chainlink/password.txt --api /chainlink/apicredentials.txt
  pg_healthdata:
    image: "postgres"
    ports:
      - "5433:5432"
    env_file:
      - healthdb.env
    volumes:
      - ~/Documents/Chainlink/chainlink-rinkeby/database:/var/lib/postgresql/data
  
  # pgadmin:
  #   image: dpage/pgadmin4
  #   env_file:
  #     - pg_admin.env
  #   ports:
  #     - "8080:80"
